service: cloudwatch-logs

provider:
  name: aws
  runtime: python3.7
  region: ap-northeast-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:DescribeLogGroups"
        - "logs:PutRetentionPolicy"
      Resource:
          - "arn:aws:logs:*:*:log-group:*"
          - "arn:aws:logs:*:*:log-group:*:log-stream:*"

functions:
  change_retention:
    handler: handler.main
    timeout: 300
    environment:
      RETENTION: 7
    events:
      - schedule: cron(0 15 * * ? *)
